const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],money=n=>'$'+Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}),fmt=n=>Number(n||0).toLocaleString(undefined,{maximumFractionDigits:6});
const apiKey=()=>sessionStorage.getItem('stockswap_rapidapi_key')||'';
function apiFetchOptions(){const key=apiKey();return{cache:'no-store',headers:key?{'x-stockswap-api-key':key}:{}}}
function updateApiStatus(msg){const active=!!apiKey(),st=$('#apiStatusDirect');st.classList.toggle('ok',active);st.querySelector('span').textContent=msg||(active?'Browser API key active':'Using server configuration');if(active&&!$('#apiKeyInputDirect').value)$('#apiKeyInputDirect').value=apiKey()}
$('#apiToggleDirect').onclick=()=>{const i=$('#apiKeyInputDirect'),show=i.type==='password';i.type=show?'text':'password';$('#apiToggleDirect').textContent=show?'Hide':'Show'};
$('#apiClearDirect').onclick=()=>{sessionStorage.removeItem('stockswap_rapidapi_key');$('#apiKeyInputDirect').value='';updateApiStatus('Using server configuration');toast('Browser API key cleared')};
$('#apiSaveDirect').onclick=async()=>{const key=$('#apiKeyInputDirect').value.trim(),btn=$('#apiSaveDirect');if(!key)return toast('Paste an API key first');sessionStorage.setItem('stockswap_rapidapi_key',key);updateApiStatus('Testing API key…');btn.disabled=true;btn.textContent='Testing…';const ok=await refresh();btn.disabled=false;if(ok){btn.textContent='Connected';updateApiStatus('API key connected');setTimeout(()=>btn.textContent='Save & Test',900)}else{btn.textContent='Try Again';updateApiStatus('API test failed')}};
updateApiStatus();
const stocks={AAPL:{name:'Apple Inc.',price:228.42,day:.0074},NVDA:{name:'NVIDIA',price:177.18,day:.0128},TSLA:{name:'Tesla',price:347.65,day:-.0092},AMZN:{name:'Amazon',price:238.57,day:.0049},MSFT:{name:'Microsoft',price:509.21,day:.0035},META:{name:'Meta',price:755.64,day:-.0031},GOOGL:{name:'Alphabet',price:245.38,day:.0061}};
const rarities=[{name:'Common',w:60,min:30,max:45},{name:'Uncommon',w:25,min:50,max:75},{name:'Rare',w:10,min:100,max:180},{name:'Epic',w:4,min:250,max:500},{name:'Legendary',w:1,min:1000,max:1000}];let state={balance:1000,holdings:{AAPL:{shares:.64,cost:142.5},NVDA:{shares:.22,cost:39.1}}},selected=null,pending=null,chart=null,series=null,renderer=null,raf=null;
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('on');setTimeout(()=>$('#toast').classList.remove('on'),1600)}
$$('[data-tab]').forEach(b=>b.onclick=()=>{$$('[data-tab]').forEach(x=>x.classList.toggle('on',x===b));$$('.view').forEach(v=>v.classList.toggle('on',v.id===b.dataset.tab));if(b.dataset.tab==='portfolio'){showList();render()}});
function pv(){return Object.entries(state.holdings).reduce((a,[t,h])=>a+h.shares*stocks[t].price,0)}function wallet(){const p=pv();$('#wallet').textContent=money(state.balance)+' USDC';$('#cash').textContent=money(state.balance);$('#stockValue').textContent=money(p);$('#total').textContent=money(state.balance+p)}
function spark(c){const t=c.dataset.spark,x=c.getContext('2d'),w=c.width,h=c.height;x.clearRect(0,0,w,h);x.strokeStyle=stocks[t].day>=0?'#9cff67':'#ff6972';x.lineWidth=2;x.beginPath();let y=h/2;for(let i=0;i<22;i++){y=Math.max(5,Math.min(h-5,y+(Math.random()-.5)*8));let px=i/21*w;i?x.lineTo(px,y):x.moveTo(px,y)}x.stroke()}
function render(){wallet();const e=Object.entries(state.holdings).filter(([,h])=>h.shares>1e-8);$('#rows').innerHTML=e.length?e.map(([t,h])=>`<div class="row" data-t="${t}"><div class="asset"><div class="ico">${t.slice(0,4)}</div><div><b>${t}</b><small>${stocks[t].name}</small></div></div><div class="cell"><b>${fmt(h.shares)}</b><small>fractional</small></div><div class="cell"><b>${money(h.shares*stocks[t].price)}</b><small>@ ${money(stocks[t].price)}</small></div><canvas class="spark" width="140" height="56" data-spark="${t}"></canvas><button class="viewBtn">View</button></div>`).join(''):'<div style="padding:60px;text-align:center;color:#7b848f;font-size:11px">No positions yet.</div>';$$('.row').forEach(r=>r.onclick=()=>openDetail(r.dataset.t));$$('[data-spark]').forEach(spark)}
function showList(){$('#list').classList.remove('off');$('#detail').classList.remove('on')}$('#back').onclick=showList;
function openDetail(t){selected=t;$('#list').classList.add('off');$('#detail').classList.add('on');$('#amount').value='0';$$('[data-range]').forEach(b=>b.classList.toggle('on',b.dataset.range==='1D'));detail();buildChart('1D');scrollTo({top:0,behavior:'smooth'})}
function detail(){if(!selected)return;const s=stocks[selected],h=state.holdings[selected]||{shares:0,cost:0},v=h.shares*s.price,p=v-h.cost;$('#dt').textContent=$('#st').textContent=selected;$('#dn').textContent=s.name;$('#dp').textContent=money(s.price);$('#dm').textContent=(s.day>=0?'+':'')+(s.day*100).toFixed(2)+'%';$('#dm').style.color=s.day>=0?'var(--g)':'var(--r)';$('#sShares').textContent=fmt(h.shares);$('#sValue').textContent=money(v);$('#sCost').textContent=h.shares?money(h.cost/h.shares):'$0.00';$('#sPnl').textContent=(p>=0?'+':'')+money(p);$('#sPnl').style.color=p>=0?'var(--g)':'var(--r)';$('#avail').textContent=fmt(h.shares)+' available';quote()}
function fallbackHistory(t,r){const cfg={'1D':[90,300],'1W':[84,7200],'1M':[90,28800],'3M':[90,86400],'1Y':[120,259200]}[r],now=Math.floor(Date.now()/1000);let p=stocks[t].price,arr=[];for(let i=cfg[0]-1;i>=0;i--){p*=1+(Math.random()-.49)*(r==='1D'?.002:.007);arr.push({time:now-i*cfg[1],value:p})}arr[arr.length-1].value=stocks[t].price;return arr}
async function marketHistory(t,r){try{let x=await fetch(`/api/chart?symbol=${encodeURIComponent(t)}&range=${r}`,apiFetchOptions());if(!x.ok)throw 0;let j=await x.json(),d=(j.bars||[]).map(b=>({time:b.time,value:b.close})).filter(b=>Number.isFinite(b.value));if(d.length>2)return d}catch(e){}return fallbackHistory(t,r)}
async function buildChart(r){if(!selected)return;const t=selected,h=$('#chart');h.innerHTML='<div style="height:100%;display:grid;place-items:center;color:#66707a;font-size:10px">Loading market data…</div>';const data=await marketHistory(t,r);if(selected!==t)return;h.innerHTML='';if(!window.LightweightCharts)return;try{chart?.remove()}catch(e){}chart=LightweightCharts.createChart(h,{width:h.clientWidth,height:h.clientHeight,layout:{background:{color:'#0d0f12'},textColor:'#707883'},grid:{vertLines:{color:'#171b20'},horzLines:{color:'#171b20'}},rightPriceScale:{borderColor:'#242a31'},timeScale:{borderColor:'#242a31',timeVisible:r==='1D'||r==='1W'},crosshair:{vertLine:{color:'#39414a'},horzLine:{color:'#39414a'}}});series=chart.addAreaSeries({lineColor:stocks[t].day>=0?'#9cff67':'#ff6972',topColor:stocks[t].day>=0?'rgba(156,255,103,.22)':'rgba(255,105,114,.2)',bottomColor:'transparent',lineWidth:2});series.setData(data);chart.timeScale().fitContent()}
$$('[data-range]').forEach(b=>b.onclick=()=>{$$('[data-range]').forEach(x=>x.classList.toggle('on',x===b));buildChart(b.dataset.range)});
function quote(){if(!selected)return;const h=state.holdings[selected]||{shares:0};let n=Math.max(0,Math.min(parseFloat($('#amount').value)||0,h.shares)),v=n*stocks[selected].price;$('#qv').textContent=money(v);$('#qr').textContent=money(v)+' USDC';$('#sellAction').disabled=!n}$('#amount').oninput=quote;$$('[data-pct]').forEach(b=>b.onclick=()=>{if(!selected)return;$('#amount').value=(state.holdings[selected].shares*+b.dataset.pct).toFixed(6);quote()});
$('#sellAction').onclick=()=>{const h=state.holdings[selected],n=Math.max(0,Math.min(parseFloat($('#amount').value)||0,h.shares));if(!n)return;const before=h.shares,proceeds=n*stocks[selected].price;h.shares-=n;h.cost=Math.max(0,h.cost*(1-n/before));state.balance+=proceeds;$('#amount').value='0';toast(`Sold ${fmt(n)} ${selected} for ${money(proceeds)}`);render();if(h.shares<1e-8)showList();else detail()};
function pick(){let r=Math.random()*100,c=0;for(const x of rarities){c+=x.w;if(r<c)return x}return rarities[0]}function prize(){const rarity=pick(),keys=Object.keys(stocks),ticker=keys[Math.floor(Math.random()*keys.length)],value=rarity.min===rarity.max?rarity.min:rarity.min+Math.random()*(rarity.max-rarity.min);return{rarity,ticker,value,price:stocks[ticker].price,shares:value/stocks[ticker].price}}
let ac;function tone(f,d=.08,v=.03,delay=0){try{ac=ac||new(window.AudioContext||window.webkitAudioContext)();const o=ac.createOscillator(),g=ac.createGain(),t=ac.currentTime+delay;o.frequency.value=f;g.gain.setValueAtTime(v,t);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g);g.connect(ac.destination);o.start(t);o.stop(t+d+.02)}catch(e){}}function particles(n){$('#particles').innerHTML='';for(let i=0;i<n;i++){let p=document.createElement('i'),a=Math.random()*6.28,d=100+Math.random()*330;p.className='particle';p.style.setProperty('--x',Math.cos(a)*d+'px');p.style.setProperty('--y',Math.sin(a)*d+'px');$('#particles').appendChild(p)}}
function texture(p){const c=document.createElement('canvas');c.width=1000;c.height=1400;const x=c.getContext('2d');const palette={Common:['#2c3138','#0d0f12','#a5abb2'],Uncommon:['#25451f','#0b1209','#9cff67'],Rare:['#17375e','#08111f','#78a9ff'],Epic:['#46235f','#110818','#ca8cff'],Legendary:['#614b17','#171006','#ffd15c']}[p.rarity.name];const g=x.createLinearGradient(0,0,1000,1400);g.addColorStop(0,palette[0]);g.addColorStop(.55,palette[1]);g.addColorStop(1,'#070809');x.fillStyle=g;x.fillRect(0,0,1000,1400);x.strokeStyle=palette[2];x.globalAlpha=.65;x.lineWidth=4;x.strokeRect(44,44,912,1312);x.globalAlpha=1;x.fillStyle='#ffffff88';x.font='700 26px Arial';x.fillText('STOCKSWAP  •  VIRTUAL POSITION',70,105);x.fillStyle='#fff';x.font='900 126px Arial';x.fillText(p.ticker,70,270);x.fillStyle='#ffffffa8';x.font='600 34px Arial';x.fillText(stocks[p.ticker].name,70,325);x.fillStyle='#ffffff10';x.fillRect(70,400,860,360);x.strokeStyle='#ffffff1f';x.lineWidth=2;x.strokeRect(70,400,860,360);x.textAlign='center';x.fillStyle=palette[2];x.font='900 250px Arial';x.fillText(p.ticker.slice(0,2),500,665);x.textAlign='left';x.fillStyle='#ffffff7d';x.font='800 28px Arial';x.fillText('YOU OWN',70,850);x.fillStyle='#fff';x.font='900 78px Arial';x.fillText(`${fmt(p.shares)} SHARES`,70,945);x.fillStyle='#ffffff7d';x.font='700 26px Arial';x.fillText(`${money(p.price)} / SHARE`,70,1000);x.fillStyle='#ffffff7d';x.font='800 28px Arial';x.fillText('POSITION VALUE',70,1100);x.fillStyle='#fff';x.font='900 88px Arial';x.fillText(money(p.value),70,1200);x.fillStyle=palette[2];x.font='900 28px Arial';x.fillText(p.rarity.name.toUpperCase(),70,1310);x.textAlign='right';x.fillStyle='#ffffff66';x.font='700 24px Arial';x.fillText('INTERACTIVE 3D CARD',930,1310);x.textAlign='left';return c}
function three(p){dispose();const h=$('#three');if(!window.THREE){h.innerHTML='<div style="height:100%;display:grid;place-items:center;color:#fff;font-weight:800">3D card unavailable</div>';return}const sc=new THREE.Scene(),cam=new THREE.PerspectiveCamera(30,h.clientWidth/h.clientHeight,.1,100),r=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'high-performance'});renderer=r;r.setPixelRatio(Math.min(window.devicePixelRatio||1,2));r.setSize(h.clientWidth,h.clientHeight,false);r.outputEncoding=THREE.sRGBEncoding;h.innerHTML='';h.appendChild(r.domElement);cam.position.z=7.7;const tx=new THREE.CanvasTexture(texture(p));tx.encoding=THREE.sRGBEncoding;tx.anisotropy=Math.min(8,r.capabilities.getMaxAnisotropy());const accent={Common:0xa5abb2,Uncommon:0x9cff67,Rare:0x78a9ff,Epic:0xca8cff,Legendary:0xffd15c}[p.rarity.name];const front=new THREE.MeshPhysicalMaterial({map:tx,roughness:.28,metalness:.12,clearcoat:.55,clearcoatRoughness:.2}),back=new THREE.MeshPhysicalMaterial({color:0x0b0e12,roughness:.35,metalness:.55,clearcoat:.25}),edge=new THREE.MeshStandardMaterial({color:accent,metalness:.75,roughness:.24}),card=new THREE.Mesh(new THREE.BoxGeometry(3.05,4.28,.18),[edge,edge,edge,edge,front,back]);sc.add(card);const glow=new THREE.Mesh(new THREE.PlaneGeometry(3.55,4.8),new THREE.MeshBasicMaterial({color:accent,transparent:true,opacity:.09,depthWrite:false}));glow.position.z=-.16;sc.add(glow);sc.add(new THREE.AmbientLight(0xffffff,1.15));const key=new THREE.DirectionalLight(0xffffff,2.4);key.position.set(3,4,5);sc.add(key);const rim=new THREE.PointLight(accent,20,20);rim.position.set(-3,-1.5,3);sc.add(rim);let targetX=.02,targetY=-.04,hover=false;h.onpointermove=e=>{const b=h.getBoundingClientRect();targetY=((e.clientX-b.left)/b.width-.5)*.5;targetX=((e.clientY-b.top)/b.height-.5)*-.34;hover=true};h.onpointerleave=()=>{targetX=.02;targetY=-.04;hover=false};function loop(){raf=requestAnimationFrame(loop);card.rotation.x+=(targetX-card.rotation.x)*.075;card.rotation.y+=(targetY-card.rotation.y)*.075;glow.rotation.copy(card.rotation);const bob=Math.sin(performance.now()/850)*.045;card.position.y=bob;glow.position.y=bob;const scale=hover?1.015:1;card.scale.x+=(scale-card.scale.x)*.08;card.scale.y+=(scale-card.scale.y)*.08;card.scale.z+=(scale-card.scale.z)*.08;r.render(sc,cam)}loop()}
function dispose(){if(raf)cancelAnimationFrame(raf);raf=null;if(renderer){renderer.dispose();renderer.domElement?.remove()}renderer=null;$('#three').innerHTML=''}function closeReveal(){pending=null;$('#reveal').className='reveal';dispose();render()}
$('#open').onclick=async()=>{if(state.balance<50)return toast('Not enough USDC');await refresh();state.balance-=50;wallet();pending=prize();const r=$('#reveal');r.dataset.rarity=pending.rarity.name;r.className='reveal on';$('#scan').textContent='COMMON';await new Promise(x=>setTimeout(x,250));r.classList.add('charge');for(const [i,l] of ['COMMON','UNCOMMON','RARE','EPIC','LEGENDARY','RARE','EPIC'].entries()){await new Promise(x=>setTimeout(x,145+i*25));$('#scan').textContent=l;tone(180+i*60)}r.classList.remove('charge');r.classList.add('burst','final');$('#scan').textContent=pending.rarity.name.toUpperCase();[392,523,784,1047].slice(0,{Common:1,Uncommon:2,Rare:3,Epic:4,Legendary:4}[pending.rarity.name]).forEach((f,i)=>tone(f,.35,.04,i*.06));particles({Common:18,Uncommon:30,Rare:55,Epic:85,Legendary:130}[pending.rarity.name]);await new Promise(x=>setTimeout(x,500));r.classList.add('card');three(pending);$('#rr').textContent=pending.rarity.name;$('#rt').textContent=`${pending.ticker} · ${money(pending.value)}`;$('#rs').textContent=`${fmt(pending.shares)} shares at ${money(pending.price)}`};
$('#keep').onclick=()=>{if(!pending)return;const h=state.holdings[pending.ticker]||{shares:0,cost:0};h.shares+=pending.shares;h.cost+=pending.value;state.holdings[pending.ticker]=h;toast(`${pending.ticker} kept`);closeReveal()};$('#sellNow').onclick=()=>{if(!pending)return;state.balance+=pending.value;toast(`${money(pending.value)} added to USDC`);closeReveal()};
async function refresh(){try{const syms=Object.keys(stocks).join(','),r=await fetch(`/api/quotes?symbols=${encodeURIComponent(syms)}`,apiFetchOptions());if(!r.ok)throw 0;const j=await r.json();for(const q of j.quotes||[]){if(!stocks[q.symbol]||!Number.isFinite(q.price))continue;stocks[q.symbol].price=q.price;if(Number.isFinite(q.changePercent))stocks[q.symbol].day=q.changePercent/100;if(q.name)stocks[q.symbol].name=q.name}render();if(selected&&$('#detail').classList.contains('on'))detail();return true}catch(e){return false}}
render();refresh();setInterval(refresh,15000);
